export const LOGIN_TOKEN = 'login/token'
export const LOGIN_ACCOUNT = 'login/account'
export const LOGIN_PWD = 'login/password'
export const LOGIN_REM = 'login/remember'
export const LOGIN_USER_INFO = 'login/userinfo'
export const LOGIN_USER_MENUS = 'login/usermenus'